### ISSUE TITLE
Cannot install Create together with The Factory Must Grow

### ISSUE THREAD

**Issue by KittenRaee** [macarooni-man/auto-mcs#102]
One replaces the other, making game either miss critical dependency of Create or lacking TFMG

**Comment by macarooni-man** [comment]
Hi @KittenRaee, thanks for putting in an issue. If the modpack imports, as far as we're concerned that works. Generally modpacks have unpredictable compatibility and that lies in the responsibility of the modpack author. [Feel free to join our Discord server](https://discord.gg/dShCFbgNYJ) for help troubleshooting modpacks from our community.
