### ISSUE TITLE
[Feature Request] Full docker image

### ISSUE THREAD

**Issue by CyberB1aze** [macarooni-man/auto-mcs#107]
Hi, I saw this project in https://selfh.st/apps/ and it looks very promising.

is it possible to have a docker image that also runs the full webui? The current one is only running with CLI i believe. 

Thanks

**Comment by macarooni-man** [comment]
Hi @CyberB1aze,

Currently the Docker image is just a host for managing the server through Telepath, our custom remote access solution with our desktop application. Feel free to learn more [on our website!](https://www.auto-mcs.com/guides/telepath)

I wrote the interface for auto-mcs in Kivy, which is a desktop graphics library with no web support. To get the functionality you requested, we'd have to completely rewrite the UI and that's not something I wish to do right now or in the near future as it took 2 years alone to do the first one in Kivy. I'm interesting in moving towards Flet, though, it won't be for a while.

If you'd like to get the full functionality of auto-mcs, I would consider looking at our Telepath implementation as mentioned before.

I take it you probably haven't used our desktop application with Telepath, though maybe you have and didn't mention it. If this is the case, what are the benefits of having a WebUI over our current implementation?

**Comment by CyberB1aze** [comment]
> Hi @CyberB1aze,
> 
> Currently the Docker image is just a host for managing the server through Telepath, our custom remote access solution with our desktop application. Feel free to learn more [on our website!](https://www.auto-mcs.com/guides/telepath)
> 
> I wrote the interface for auto-mcs in Kivy, which is a desktop graphics library with no web support. To get the functionality you requested, we'd have to completely rewrite the UI and that's not something I wish to do right now or in the near future as it took 2 years alone to do the first one in Kivy. I'm interesting in moving towards Flet, though, it won't be for a while.
> 
> If you'd like to get the full functionality of auto-mcs, I would consider looking at our Telepath implementation as mentioned before.
> 
> I take it you probably haven't used our desktop application with Telepath, though maybe you have and didn't mention it. If this is the case, what are the benefits of having a WebUI over our current implementation?

Hi, Thanks for the reply

I probably didnt understand the project as I thought he UI elements were from a webui and not a desktop application UI. I have not tried running the desktop version. that is a whole different project and would be a massive amount of work.

for services in general (including running minecraft servers), I feel that it is more resource efficient to run them on headless servers than having a full desktop OS, linux server OS like debian or Ubuntu are very resource efficient. A lot of people run a lot of different self hosted services they use on a day to day basis on their own hardware/ VPS they control. 

docker images makes hosting these things very convenient, and running a container on a headless linux server OS of a VM instead of installing an application natively on a desktop OS has a lot of upsides. 

Currently for minecraft I use the crafty controller docker image.

**Comment by macarooni-man** [comment]
@CyberB1aze 

You make a very fair point! That's the reason I added headless mode actually so you can do just that. The primary use case of Telepath from our user base is using the desktop app on a device that's not the server, and from the app once you connect it you get the full experience on the remote server running headless, but from the app. I hope that makes sense.

Also, the desktop app automatically updates if you want, but usually it's not even necessary to update it if the Telepath protocol hasn't changed (which is only the case for major releases).

If you'd like to try it out, continue running the Docker container and try pairing it by [getting the desktop app](https://www.auto-mcs.com/download) on another device and following the instructions in that article. I'm curious to hear your feedback!

**Comment by CyberB1aze** [comment]
I see, so the app will run the servers on the docker instance, providing the UI for it as well. I will definitely try it out. Thanks!
