### ISSUE TITLE
Browse plugins. Import multiple plugins at same time.

### ISSUE THREAD

**Issue by Greninja9257** [macarooni-man/auto-mcs#109]
title

**Comment by macarooni-man** [comment]
Hi @Greninja9257,

You can already import multiple plugins at the same time, some operating systems don't allow selecting multiple files from the file browser. This isn't something I can fix unfortunately.

Alternatively, on every operating system you can drag and drop a selection of .jar files into the mod manager and import them all at once.

If you can provide more information on what you're looking for I'll reopen this, but with the limited information you've provided this is already implemented.

**Comment by Greninja9257** [comment]
Browse plugins.

**Comment by macarooni-man** [comment]
> Browse plugins.

I hope this doesn't come off as rude, but I genuinely have no idea what you mean, if you'd like to elaborate I'm happy to listen to your ideas, but saying "browse plugins" doesn't give any insight into what you're requesting.

If you're referring to a built-in browser to download mods/plugins, this has already been available as well.
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/e38a7ca2-9f78-4038-bdb6-45a9cb4b9cad" />

**Comment by Greninja9257** [comment]
Like if you dont type anything, you can just browse plugins like in falixnodes.net
