### ISSUE TITLE
Bug on Changing Server Distribution

### ISSUE THREAD

**Issue by Jason-Espiritu** [macarooni-man/auto-mcs#112]
**Describe the bug**
Trying to change my Vanilla Server to Fabric results in an Exception error during Migrating add-ons
Reason for changing server Distribution was to have the capability to install plugins / mods in the future on the existing server

**To Reproduce**
1. Go to Settings in a Vanilla Server
2. Click on Change 'Server.jar'
3. Select a distribution to change (in this case it's Fabric)
4. Click change Server then gets the error on Migrating Add-ons

**auto-mcs Configuration**
- I'm not currently using Telepath
- Currently using the GUI version of auto-mcs (ver: 2.2.5)

**Operating System and platform (please complete the following information):**
 - OS: Windows 10 22H2
 - Type of OS:  Windows
 - Architecture: x64

**Crash Log**
==============================================================================================================================
||                                             Auto-MCS Exception:    58-2e0908                                             ||
||                                             "Congratulations! It's a pizza!"                                             ||
==============================================================================================================================

    General Info:
        
        Severity:          Error
        
        Version:           2.2.5 - Windows (Windows-10-10.0.19045-SP0)
        Online:            True
        UI Language:       English (en)
        Sub-servers:       None
        Proxy (playit):    Active
        Telepath client:   Inactive
        Telepath server:   Inactive

        Processor info:    6 (6) C/T @ 2.38 GHz (64-bit)
        Used memory:       5.78 / 7 GB

    Time of AME:

        11:04:41 AM  12/21/2024

    Application path at time of AME:

        Migrating Server @ 11:04:15 AM

    
    
    Last interaction at time of AME:

        MainButton (Change 'Server.Jar') @ 11:04:13 AM
    
    

    AME traceback:
        
        Error information:
        
            'MigrateServerProgressScreen' failed on step 4: Migrating add-ons
            

        Exception Summary:
            AttributeError: 'dict' object has no attribute 'append'
            (File "constants.py", line 2902, in iter_addons)

        Traceback (most recent call last):
          File "menu.py", line 9267, in execute_steps
          File "constants.py", line 2902, in iter_addons
        AttributeError: 'dict' object has no attribute 'append'

**Expected behavior**
- Should complete the process and Change my Server distributor from Vanilla to Fabric

**Screenshots**
![image](https://github.com/user-attachments/assets/4d7988a5-17a5-44bd-b3c7-6dbfdeccb7f7)

**Additional context**
- I haven't installed add-ons when I created the Vanilla Server
- I've been using auto-mcs for 4 days so I'm relatively new to this software

**Comment by macarooni-man** [comment]
@Jason-Espiritu hey there, thanks for the detailed report! This has been fixed in 3216c3474481b5c96e2be0bd94c0f49dbd8f6308

[If you're willing to try to latest build for this fix, I'd love to hear if it works for you as well](https://github.com/macarooni-man/auto-mcs/actions/runs/12442180234)

This was caused by a conflicting flags to prevent processing of add-ons with Vanilla servers. Really appreciate you bringing this to my attention!
<img width="604" alt="image" src="https://github.com/user-attachments/assets/3c52923e-c883-4d05-bd05-2ef9903b77ef" />

**Comment by Jason-Espiritu** [comment]
Just tried the dev build today and it's now working as intended.
Didn't expect a fast response but I appreciate it.
And also thanks for the detailed explanation as to why it's causing errors, it's just something I really like as a fellow developer.

Happy Holidays!

**Comment by macarooni-man** [comment]
Great to hear! Thanks for taking a look, and this fix will be available in the next update. Feel free to let us know if you have any more issues!

Take care, and happy holidays to you as well 😀
