### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by yesBad** [macarooni-man/auto-mcs#21]
Hi there! Looks like a wonderful new software. I saw you already had some thoughts about this, just decided it could be added here as an issue.

I also wonder, how have you thought about this exactly? As currently one could make a simple image with NoVNC and make the app accessable via WebUI. The firewall stuff wouldn't work, but otherwise it would probably work.

I will personally take a look at spinning some dockerization with NoVNC. And leave some stuff about it here for those interested.

**Comment by macarooni-man** [comment]
> Hi there! Looks like a wonderful new software. I saw you already had some thoughts about this, just decided it could be added here as an issue.
> 
> I also wonder, how have you thought about this exactly? As currently one could make a simple image with NoVNC and make the app accessable via WebUI. The firewall stuff wouldn't work, but otherwise it would probably work.
> 
> I will personally take a look at spinning some dockerization with NoVNC. And leave some stuff about it here for those interested.

Hello! Thanks for posting an issue, I like your idea a lot! The main dilemma I've had with this is the accessibility of install, and the efficacy of a WebUI.

NoVNC was my solution as we;;, though I'm still pondering how to make a streamlined setup for the end user to decide whether they want that feature or not. Some people wouldn't want the added complexity of a Docker installation along with an exposed WebUI.

**Comment by yesBad** [comment]
I have made a working NoVNC powered docker build of auto-mcs, source for the Dockerfile & extras are available at: https://github.com/yesBad/auto-mcs/tree/docker

If you would like to test it out, please feel free to do so as I have published a ghcr.io image: ghcr.io/yesbad/auto-mcs:novnc
docker-compose is like so; https://github.com/yesBad/auto-mcs/blob/docker/docker-compose.yml

This dockerization I've done requires you to have "non root" Docker install, which is basically the basic stuff nowdays gladly.

![Screenshot_20231230_151324](https://github.com/macarooni-man/auto-mcs/assets/87938689/dbf4c52e-ed50-47b7-a3ef-70302222629f)


Please **do not expose the NoVNC to public**, it is in no way secure.. Keep it local & only for you!
This is only for testing & development, it is very uh shitty implementation, but it works! :D

**Comment by DevSoleo** [comment]
Works great ! Doing the `chown` command seems to be necessary for this to work !
![image](https://github.com/macarooni-man/auto-mcs/assets/27769970/e6dfdc40-c04b-4af5-9e16-44df6ba2c302)

**Comment by yesBad** [comment]
Yeah setting the UID & GID to 1000 is necessary.

**Comment by jamesisacutedog** [comment]
In Linuxserver.io docker images, there is options to set this. See below.
`---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
`
Maybe we add this way? I am currently researching how this is done

**Comment by jamesisacutedog** [comment]
See [This](https://docs.linuxserver.io/general/understanding-puid-and-pgid/)

**Comment by yesBad** [comment]
> In Linuxserver.io docker images, there is options to set this. See below. `--- version: "2.1" services: qbittorrent: image: lscr.io/linuxserver/qbittorrent:latest container_name: qbittorrent environment: - PUID=1000 - PGID=1000 - TZ=Etc/UTC - WEBUI_PORT=8080 volumes: - /path/to/appdata/config:/config - /path/to/downloads:/downloads ports: - 8080:8080 - 6881:6881 - 6881:6881/udp restart: unless-stopped ` Maybe we add this way? I am currently researching how this is done

Eh kind of useless, but I guess it could be nice QOL.

**Comment by jamesisacutedog** [comment]
Makes everyone’s life’s easier so it’s better.

**Comment by tarosbubbletea** [comment]
> I have made a working NoVNC powered docker build of auto-mcs...

By the way there's no file picker package installed in the container, so the "importing external servers" feature is broken
![image](https://github.com/macarooni-man/auto-mcs/assets/6438425/a38944ab-bce6-4b94-8cca-cae2e0b01e0c)

**Comment by yesBad** [comment]
Yeah I'm aware a couple features are borked. (i.e all that open the file manager or ask for file etc)

**Comment by macarooni-man** [comment]
> > I have made a working NoVNC powered docker build of auto-mcs...
> 
> By the way there's no file picker package installed in the container, so the "importing external servers" feature is broken

@tarosbubbletea do you by chance have any suggestions on how to get a file picker to be passed through to the host?

**Comment by yesBad** [comment]
I'll be adding WIP file support next week and the env UID/GID

**Comment by pinkyplant** [comment]
Any updates on this? And would it maybe be possible to move the forked repository to a branch here for making it easier to find and QoL?

**Comment by Alechuu** [comment]
FYI: #85

**Comment by macarooni-man** [comment]
This is now implemented:
https://github.com/macarooni-man/auto-mcs/pull/88

Docs are available on our Docker Hub page:
https://hub.docker.com/r/macarooniman/auto-mcs
