### ISSUE TITLE
[WIN] Crash when system language is not English

### ISSUE THREAD

**Issue by RafalKedziora** [macarooni-man/auto-mcs#29]
![image](https://github.com/macarooni-man/auto-mcs/assets/17769845/0528b94c-24b0-4646-9689-17d6c66c4416)

**Comment by macarooni-man** [comment]
> ![image](https://private-user-images.githubusercontent.com/17769845/293799946-0528b94c-24b0-4646-9689-17d6c66c4416.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyOTc4OTQsIm5iZiI6MTcwNDI5NzU5NCwicGF0aCI6Ii8xNzc2OTg0NS8yOTM3OTk5NDYtMDUyOGI5NGMtMjRiMC00NjQ2LTk2ODktMTdkNmM2NmM0NDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDE1NTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYTZhMzJmMDUxNGI1NzlkZDgwOTFiOWNhNDEzODg0NDg2MTFlZjg1NTU1MDI2ZDIzYjdiNTUxZjhhODgyODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zI6sjXftMY4eNscKtYMzwdWaZa2kMlPM2WNXl_bH9Pw)

This is because your system language is not set to English. I'm still looking into this!
