### ISSUE TITLE
Very high CPU load

### ISSUE THREAD

**Issue by HubbaBob** [macarooni-man/auto-mcs#40]
Hi,

really cool project - thanks!

However when testing this on my linux machines on ubuntu 22.04 I am always struck with maxed out cpu cores and huge CPU load. Machines are a bit dated (e.g. i7-2620M) but when using the original MC server or the ones from linuxgsm I barely see any CPU load at all.

Is this to be expected with auto-cms or is there a bug somewhere?

Thx!

**Comment by macarooni-man** [comment]
Hello there, hope you're doing well! I'm curious, are you using Mesa for your OpenGL renderer? I've seen this before with virtual rendering and it's likely that the UI is being rendered in software, rather than on a GPU with a proper driver. Can you send me the output of `inxi -bx`?

**Comment by HubbaBob** [comment]
Hi, yes makes sense, didn't think about the UI. Also tried to run it virtualized and had the same problem. Inxi output below.

It would be great to have a console UI or maybe a WebUI which is not depended on a dedicated GPU. That would make it easier to run it virtualized...

```
System:
  Kernel: 5.15.0-92-generic x86_64 bits: 64 Desktop: Xfce 4.16.0
    Distro: Ubuntu 22.04.3 LTS (Jammy Jellyfish)
Machine:
  Type: Laptop System: LENOVO product: 4174P4G v: ThinkPad T420s
    serial: <superuser required>
  Mobo: LENOVO model: 4174P4G serial: <superuser required> UEFI: LENOVO
    v: 8CET49WW (1.29 ) date: 09/14/2011
Battery:
  ID-1: BAT0 charge: 33.8 Wh (100.0%) condition: 33.8/38.9 Wh (87.1%)
CPU:
  Info: dual core Intel Core i7-2620M [MT MCP] speed (MHz): avg: 1487
    min/max: 800/3400
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics
    driver: i915 v: kernel
  Device-2: Chicony integrated camera type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting
    unloaded: fbdev,vesa gpu: i915 resolution: 1600x900~60Hz
  OpenGL: renderer: Mesa Intel HD Graphics 3000 (SNB GT2)
    v: 3.3 Mesa 23.0.4-0ubuntu1~22.04.1
Network:
  Device-1: Intel 82579LM Gigabit Network driver: e1000e
  Device-2: Intel Centrino Ultimate-N 6300 driver: iwlwifi
Drives:
  Local Storage: total: 1.14 TiB used: 152.28 GiB (13.0%)
Info:
  Processes: 360 Uptime: 2d 2h 8m Memory: 15.5 GiB used: 8.52 GiB (55.0%)
```

**Comment by macarooni-man** [comment]
@HubbaBob thanks for providing the output! It does appear as though you're running this with software rendering which would explain the high CPU utilization. I actually had a Windows only version that ran in the commandline, but is now insecure and outdated.

In the current state of auto-mcs, implementing such behavior would require a complete rewrite of the interface and thus not something I plan to do for a while. Definitely down the line, though.

May I ask what virtualization stack you are running? I didn't have this issue with KVM/QEMU, Hyper-V, or VirtualBox. I'm curious as I'd like to recreate the issue.

**Comment by HubbaBob** [comment]
@macarooni-man, I tried it on a headless server running Proxmox which is using KVM/QEMU under the hood afaik. Naturally this will also resort to software rendering and therefore a high load.

Thx for the great project, I'll have to wait for a docker version or a slim UI though :)

Cheers HB

**Comment by macarooni-man** [comment]
https://github.com/kivy/kivy/issues/3726

@HubbaBob it could be exacerbated by framerate. I'm curious, if you limit it with a tool like MangoHUD to 60 FPS does it resolve the issue? If this fixes it I'll just enable VSync.

**Comment by macarooni-man** [comment]
Performance issues have been resolved by the following:
- Decreased maximum framerate
- Enabled VSync
- Updated Kivy to 2.1.0 on Linux

I was able to reproduce the issue during our Docker tests, and the issue has now been resolved.
