### ISSUE TITLE
Import support for ServerPackCreator ZIPs and Servers

### ISSUE THREAD

**Issue by Giingu** [macarooni-man/auto-mcs#51]
Hey,

I use ServerPackCreator to automatically create server-side versions of my modpacks, it is quite a helpful and powerful tool as it eliminates a lot of the tedious work of having to figure out which mods are needed server-side.

Would love to be able to import these into Auto MCs to quickly run and testing, as my modpacks usually contain 600+ mods it's bound to have many problems which are easier and quicker to spot and fix with something like Auto MCs.

Currently, if I try to import the ServerPackCreator-created folder to AutoMCs it rejects it saying "This server is not valid or is corrupt".

Here is the tool: https://github.com/Griefed/ServerPackCreator

Thanks for creating Auto MCs, it's awesome and I see a lot of potential in it.

**Comment by macarooni-man** [comment]
> Hey,
> 
> I use ServerPackCreator to automatically create server-side versions of my modpacks, it is quite a helpful and powerful tool as it eliminates a lot of the tedious work of having to figure out which mods are needed server-side.
> 
> Would love to be able to import these into Auto MCs to quickly run and testing, as my modpacks usually contain 600+ mods it's bound to have many problems which are easier and quicker to spot and fix with something like Auto MCs.
> 
> Currently, if I try to import the ServerPackCreator-created folder to AutoMCs it rejects it saying "This server is not valid or is corrupt".
> 
> Here is the tool: https://github.com/Griefed/ServerPackCreator
> 
> Thanks for creating Auto MCs, it's awesome and I see a lot of potential in it.

Hello there, hope you're doing well! Actually, auto-mcs should have support for this feature but you would import the modpack as a .zip file, not as a standalone server. Please let me know if this works for you!

![image](https://github.com/macarooni-man/auto-mcs/assets/72526467/4a5a08a9-87d0-4d2f-8aa3-c6bf4ed3dec4)
