### ISSUE TITLE
Replace ngrok tunneling

### ISSUE THREAD

**Issue by macarooni-man** [macarooni-man/auto-mcs#52]
With the addition of the data cap to ngrok's free tier, it makes it challenging to use as a permanent solution for tunneling. Currently, we're looking to replace ngrok with playit.gg as it supports 4 concurrent tunnels with both TCP and UDP, allowing for tunneling a Geyser configuration as well. The following will need to be considered during the replacement:

- [x] Refactor all the code and variable names that explicitly mention ngrok
- [x] Upon the replacement, notify users with the ngrok executable installed that it's no longer supported and present them with the option to replace it
- [x] Modify `auto-mcs.ini` files to replace `enableNgrok` with a brand-agnostic name such as `useTunneling` and add a condition in the code to replace that variable in memory to prevent errors with importing legacy servers
- [x] Figure out a way to detect the presence of the alternative, and if the alternative supports a backend web request like ngrok's config page to grab the IP addresses
- [x] Figure out a way to automate the initiation and closure of a tunnel with a specific port and protocol similar to the ngrok CLI method
- [x] Edit the Server Manager panel to show the Local IP, public IP, and Bedrock IP when hovering over it for a second instead of right clicking for that info

**Comment by macarooni-man** [comment]
After extensive testing with playit.gg's CLI agent, it's extremely difficult to replace the temporary tunnel offered by ngrok which allows you to set a new port on the fly. The CLI agent doesn't allow you to create functional tunnels, or delete them, even after authentication with an account. With relying entirely on the user for configuring the tunnels, it's not something I wish to support unless it can be automated.

**Comment by yesBad** [comment]
frp/Rathole support for custom tunnel 👀

**Comment by macarooni-man** [comment]
Replaced with playit.gg in:

https://github.com/macarooni-man/auto-mcs/commit/fec7c6172821d2b0a399fafde77869ce19855ff0
https://github.com/macarooni-man/auto-mcs/commit/6574942927f58f980379f74f184db033cc9cc9a0
