### ISSUE TITLE
Server Import Issues

### ISSUE THREAD

**Issue by 5ghzx** [macarooni-man/auto-mcs#61]
Trying to import a 1.11.1 vanilla server, checked that it runs, still fails to import. Generic "there was an issue, please try again." I tried with multiple other servers, only one worked, and I don't know why.

**Comment by 5ghzx** [comment]
Don't know whether there is a log.txt, or I would send it.

**Comment by macarooni-man** [comment]
> Don't know whether there is a log.txt, or I would send it.

Hi there, out of curiosity, does the server have a startup script?

I would suggest downloading the latest artifact from actions and seeing if that works for you.

**Comment by 5ghzx** [comment]
I don't believe so, I never set one up and there is not auto generated one because it is a 1.11.1 server

**Comment by 5ghzx** [comment]
works with latest artifacts build

**Comment by 5ghzx** [comment]
You should publicize this more, this is an amazing tool.

**Comment by 5ghzx** [comment]
Happened again, when importing valhesia 3 3.5.1 server, there is an error

**Comment by macarooni-man** [comment]
> Happened again, when importing valhesia 3 3.5.1 server, there is an error

Is this a modpack? If so, make sure you're importing the server as a `.zip` and not like you'd import a standard server, it may not work as expected. If it's a modpack, please post the link to the exact version you downloaded!

**Comment by 5ghzx** [comment]
It is not a zip, it's a server. It doesn't have as server.jar though, just a startup .bat.

**Comment by 5ghzx** [comment]
![image](https://github.com/macarooni-man/auto-mcs/assets/77870202/023e0cbf-b0ea-471b-8ebd-ac684104a3c5)
this is the structure of the folder

**Comment by macarooni-man** [comment]
> ![image](https://private-user-images.githubusercontent.com/77870202/341998298-023e0cbf-b0ea-471b-8ebd-ac684104a3c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwOTU2NTcsIm5iZiI6MTcxOTA5NTM1NywicGF0aCI6Ii83Nzg3MDIwMi8zNDE5OTgyOTgtMDIzZTBjYmYtYjBlYS00NzFiLThlYmQtYWM2ODQxMDRhM2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDIyMjkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MDkzZWUwY2Q4NzVkMDlkM2YzNDM2OTE0NWNiYmM0ODRmZDU4OTRkYzg0OWM0NDg3Zjc2ODljNTE3YjBmMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.73K05tVv0BWKtglq7VezNAvV2cGzdtb0hMbv9v6CaBY) this is the structure of the folder

auto-mcs will only let you import a modpack as a `.zip` file. Since this server doesn't have a `.jar` file other than the forge installer, I don't believe it's able to recognize just the installer. If Forge was installed auto-mcs would be able to recognize the server. You could compress the files into a `.zip` file and you should be able to import this server as a modpack. It's kind of inconvenient, but I will continue looking into a better way to import a modpack that's extracted.

**Comment by 5ghzx** [comment]
Can it identify this? 
![image](https://github.com/macarooni-man/auto-mcs/assets/77870202/c3754651-eb8e-4738-856e-80d8bacfbc36)

**Comment by macarooni-man** [comment]
> Can it identify this? 
> ![image](https://github.com/macarooni-man/auto-mcs/assets/77870202/c3754651-eb8e-4738-856e-80d8bacfbc36)
> 

Try it, I believe it would recognize Forge

**Comment by macarooni-man** [comment]
Hi @5ghzx, are you still having issues with this?

**Comment by macarooni-man** [comment]
Closing as no response was recieved about this
