### ISSUE TITLE
Add ability to switch version of modloader

### ISSUE THREAD

**Issue by hl2jeep** [macarooni-man/auto-mcs#77]
currently there seems to be no way to change the modloader version, it just uses the latest, some mods require older versions of modloader, such as my modpack requiring a slightly older forge release. currently the only way to override this is to manually replace the server jar.

**Comment by macarooni-man** [comment]
Hi @hl2jeep! What do you think would be the optimal way to implement this? It would be challenging to implement a feature that automatically pulls a list of all modloader versions, and build a scraper to get the link for them. Could you help find a link where I can access these?

**Comment by hl2jeep** [comment]
> Hi @hl2jeep! What do you think would be the optimal way to implement this? It would be challenging to implement a feature that automatically pulls a list of all modloader versions, and build a scraper to get the link for them. Could you help find a link where I can access these?

I think the simplest way would be to do the same as the Minecraft version selector, simply display a box with an input field for the version number, maybe add a link to the modloaders page to allow people to get the version from there? One more thing I would like to mention that I forgot to is neoforge support should be added as on newer versions (1.20.6 and onward) neoforge is basically replacing forge.

**Comment by macarooni-man** [comment]
> > Hi @hl2jeep! What do you think would be the optimal way to implement this? It would be challenging to implement a feature that automatically pulls a list of all modloader versions, and build a scraper to get the link for them. Could you help find a link where I can access these?
> 
> I think the simplest way would be to do the same as the Minecraft version selector, simply display a box with an input field for the version number, maybe add a link to the modloaders page to allow people to get the version from there? One more thing I would like to mention that I forgot to is neoforge support should be added as on newer versions (1.20.6 and onward) neoforge is basically replacing forge.

@hl2jeep I'm looking into adding support for NeoForge and Quilt, though, it's a pretty complicated process to integrate it like the other distributions. I can't say when that will be implemented. I'll open another issue for that.

**Comment by macarooni-man** [comment]
Due to challenges with scraping Forge versions, this is unlikely to be implemented until an API is exposed for easy access to the modloader versions.

**Comment by hl2jeep** [comment]
You need to talk to the neoforge and fabric Devs about it, they're likely
to help you out. Forge (the regular one) won't cooperate because of it's
stubborn owner. But the others will.
