### ISSUE TITLE
Make import a server better

### ISSUE THREAD

**Issue by Greninja9257** [macarooni-man/auto-mcs#87]
When you import a server the jar file needs to be just the right name as the original jar file. Make it able to detect what the jar file mod loader is and where it is so you don't need to change the name.

**Comment by macarooni-man** [comment]
> When you import a server the jar file needs to be just the right name as the original jar file. Make it able to detect what the jar file mod loader is and where it is so you don't need to change the name.

Hi! I'm not sure exactly what you mean:

The import server functionality actually detects what .jar file you specified in the launch script. If you don't have a launch script, it tries to find any .jar file in the directory, so it doesn't actually find anything based on the name. If you're having issues, feel free to join our Discord server and we'll help you out!

**Comment by macarooni-man** [comment]
Unable to reproduce as the issue was not clarified. As mentioned, the described behavior is not present as the .jar name is dynamically determined from the run script.

**Comment by Greninja9257** [comment]
To clarify, when I import a server, the server has a server .jar file. When I import a server and the .jar file does not have the same name as the official servers .jar file name is, it won't import. For example, the official paper server .jar file name is paper-1.21.1-100.jar and if you name it something like awesomeserver.jar it won't upload.

**Comment by macarooni-man** [comment]
> To clarify, when I import a server, the server has a server .jar file. When I import a server and the .jar file does not have the same name as the official servers .jar file name is, it won't import. For example, the official paper server .jar file name is paper-1.21.1-100.jar and if you name it something like awesomeserver.jar it won't upload.

This must be because the file name wasn't changed in your start.bat as well. Like I mentioned prior, auto-mcs gets the .jar name from the run script, not the .jar file itself
