### ISSUE TITLE
You should add a way to upload your own amscripts on website

### ISSUE THREAD

**Issue by Greninja9257** [macarooni-man/auto-mcs#93]
title. And make auto-mcs app able to download uploaded ones from website.

**Comment by macarooni-man** [comment]
> title. And make auto-mcs app able to download uploaded ones from website.

Hello! Actually that's what the amscript library in the github is for, I'd like to have users submit their scripts. Currently, there's no formal method for doing so because I'd like to look at them first, but feel free to join the Discord and share your scripts in the amscript channel!

**Comment by macarooni-man** [comment]
I'm going to close this request for now until we have user submitted scripts. Currently, the scripts available in our repo can be downloaded directly inside the app.

For now, if you have a script you'd like to upload, please submit a thread [on this channel](https://discord.com/channels/1186409550375563384/1186419104203153429) in our Discord server, or shoot us an email at `help@auto-mcs.com`.
